[versions]
agp = "8.11.0"
activity = "1.10.1"
splashscreen = "1.0.1"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library" }

