[versions]
agp = "8.9.2"
activity = "1.10.1"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library" }

